source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

project 'Sample'
workspace '../../FileBrowserWorkspace'

target 'Sample' do
    pod 'FileBrowser', :path => '../../FileBrowser.podspec'
end
